config/routes.rb
Rails.application.routes.draw do
  resources :resumes, only: [:create]
  root 'root#index'
end

app/models/resume.rb
class Resume
  attr_accessor :json, :message

  def initialize(params = {})
    file_content = params[:resume].try(:read)
    self.json = JSON.parse(file_content)
  rescue => e
    self.message = e.message
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
  # POST /resumes
  def create
    @resume = Resume.new(permitted_params)
  end

  private

  def permitted_params
    params.permit(:resume)
  end
end

app/controllers/root_controller.rb
class RootController < ApplicationController
  # GET /
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/resumes_helper.rb
module ResumesHelper
  def partial_name(resume)
    resume.message.blank? ? 'resume' : 'error'
  end

  def json_to_html(json)
    json.inject('') do |html, arr|
      html << parse_struct(arr.first, arr.last)
      html
    end.html_safe
  end

  def parse_struct(text, struct)
    html_tag = struct['html_tag']
    return '' if html_tag.blank?
    inner_html = parse_html(struct['innerHTML'])
    after_html = parse_html(struct['afterHTML'])
    css = parse_css(struct['css'])
    text ||= struct['text']
    "<#{html_tag} style=\"#{css}\">#{text}#{inner_html}</#{html_tag}>\n#{after_html}"
  end

  def parse_css(css)
    css ||= {}
    css.inject('') do |style, arr|
      style << "#{arr.first}:#{arr.last};"
      style
    end
  end

  def parse_html(array)
    array ||= []
    array.inject('') do |html, struct|
      html << parse_struct(nil, struct)
      html
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Resume/CV JSON App</title>
    <%= csrf_meta_tags %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
      <%= yield %>

      <footer class="footer">
        <p>© Resume/CV JSON App 2017</p>
      </footer>
    </div>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </body>
</html>

app/views/resumes/_error.html.erb
<div class="alert alert-danger" role="alert">
  <samp><%= @resume.message %></samp>
</div>

app/views/resumes/_resume.html.erb
<div class="card-block"><%= json_to_html(@resume.json) %></div>

app/views/resumes/create.js.erb
$("#resume").html("<%= escape_javascript(render partial_name(@resume)) %>");

app/views/root/index.html.erb
<div class="jumbotron">
  <h1 class="display-3">Resume/CV JSON App</h1>
</div>

<div>
  <%= form_tag resumes_path, method: :post, remote: true, multipart: true do -%>
    <div class="col-lg-12">
      <div class="input-group">
        <input type="file" name="resume" class="form-control">
        <span class="input-group-btn">
          <button class="btn btn-success" type="submit">Upload!</button>
        </span>
      </div>
    </div>
  <% end -%>

  <hr>
  <div id="resume" class="card"></div>
</div>

<small class="form-text text-muted">
  JSON Rules:
  <br>
  <code>"text" (this text goes inside for the html tag) => Hash</code>
  <br>
  <code>{</code>
  <div style="white-space: pre;">
    <code>"html_tag" => String (Required)</code>
    <code>"css" => Hash (key: css property, value: property value)</code>
    <code>"innerHTML" => Array of Hashes</code>
    <code>"afterHTML" => Array of Hashes</code>
    <code>"text" => String (Optional, overrides the key text or set the text)</code>
  </div>
  <code>}</code>
  <br>
  <br>
  Example1 Input: <code>{"My Name": {"html_tag": "h1", "css": {"text-align": "center"}, "afterHTML": [{"html_tag": "p", "text": "something else"}], "innerHTML": []}}</code>
  <br>
  Example1 Output: <code>&lt;h1 style="text-align: center"&gt;My Name&lt;/h1&gt;&lt;p&gt;something else&lt;/p&gt;</code>
  <br>
  <br>
  Example2 Input: <code>{"My Name": {"html_tag": "h1", "css": {"text-align": "center"}, "afterHTML": [], "innerHTML": [{"html_tag": "small", "text": "something else"}]}}</code>
  <br>
  Example2 Output: <code>&lt;h1 style="text-align: center"&gt;My Name&lt;small&gt;something else&lt;/small&gt;&lt;/h1&gt;</code>
</small>

<hr>